/* eslint-disable */
module.exports = [
    {
      "nodeId": "b-1607152742796",
      "pageId": "p-1607152742791-/pages/index/index",
      "type": "element",
      "tagName": "div",
      "id": "",
      "className": "h5-div node-b-1607152742796 ",
      "style": "",
      "isImage": false,
      "useTemplate": false,
      "isLeaf": false,
      "isSimple": true,
      "content": "",
      "childNodes": [
        {
          "nodeId": "b-1607152742797",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "ul",
          "id": "",
          "className": "h5-ul node-b-1607152742797 tabbar",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": true,
          "content": "",
          "childNodes": [
            {
              "nodeId": "b-1607152742798",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "li",
              "id": "",
              "className": "h5-li node-b-1607152742798 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": false,
              "isSimple": true,
              "content": "",
              "childNodes": [
                {
                  "nodeId": "b-1607152742799",
                  "pageId": "p-1607152742791-/pages/index/index",
                  "type": "element",
                  "tagName": "a",
                  "id": "",
                  "className": "h5-a node-b-1607152742799 link router-link-exact-active router-link-active",
                  "style": "",
                  "isImage": false,
                  "useTemplate": false,
                  "isLeaf": true,
                  "content": "aaa",
                  "isSimple": false,
                  "childNodes": []
                }
              ]
            },
            {
              "nodeId": "b-1607152742801",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "text",
              "content": " ",
              "className": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": false,
              "isSimple": false,
              "childNodes": []
            },
            {
              "nodeId": "b-1607152742802",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "li",
              "id": "",
              "className": "h5-li node-b-1607152742802 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": false,
              "isSimple": true,
              "content": "",
              "childNodes": [
                {
                  "nodeId": "b-1607152742803",
                  "pageId": "p-1607152742791-/pages/index/index",
                  "type": "element",
                  "tagName": "a",
                  "id": "",
                  "className": "h5-a node-b-1607152742803 link",
                  "style": "",
                  "isImage": false,
                  "useTemplate": false,
                  "isLeaf": true,
                  "content": "bbb",
                  "isSimple": false,
                  "childNodes": []
                }
              ]
            }
          ]
        },
        {
          "nodeId": "b-1607152742805",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742806",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "div",
          "id": "",
          "className": "h5-div node-b-1607152742806 cnt",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": true,
          "content": "",
          "childNodes": [
            {
              "nodeId": "b-1607152742807",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "p",
              "id": "",
              "className": "h5-p node-b-1607152742807 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": true,
              "content": "I am aaa",
              "isSimple": false,
              "childNodes": []
            },
            {
              "nodeId": "b-1607152742809",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "text",
              "content": " ",
              "className": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": false,
              "isSimple": false,
              "childNodes": []
            },
            {
              "nodeId": "b-1607152742810",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "p",
              "id": "",
              "className": "h5-p node-b-1607152742810 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": true,
              "content": "route: /test/aaa",
              "isSimple": false,
              "childNodes": []
            }
          ]
        },
        {
          "nodeId": "b-1607152742812",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742813",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "button",
          "id": "",
          "className": "h5-button node-b-1607152742813 btn",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": true,
          "content": "console global",
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742815",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742816",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "button",
          "id": "",
          "className": "h5-button node-b-1607152742816 btn",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": true,
          "content": "throw an error",
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742818",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742819",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "button",
          "id": "",
          "className": "h5-button node-b-1607152742819 btn",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": true,
          "content": "update style",
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742821",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742822",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "div",
          "id": "",
          "className": "h5-div node-b-1607152742822 ",
          "style": "margin-left:20px;",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": true,
          "content": "",
          "childNodes": [
            {
              "nodeId": "b-1607152742823",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "p",
              "id": "",
              "className": "h5-p node-b-1607152742823 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": false,
              "isSimple": true,
              "content": "",
              "childNodes": [
                {
                  "nodeId": "b-1607152742824",
                  "pageId": "p-1607152742791-/pages/index/index",
                  "type": "text",
                  "content": "这是",
                  "className": "",
                  "isImage": false,
                  "useTemplate": false,
                  "isLeaf": false,
                  "isSimple": false,
                  "childNodes": []
                },
                {
                  "nodeId": "b-1607152742825",
                  "pageId": "p-1607152742791-/pages/index/index",
                  "type": "element",
                  "tagName": "span",
                  "id": "",
                  "className": "h5-span node-b-1607152742825 ",
                  "style": "",
                  "isImage": false,
                  "useTemplate": false,
                  "isLeaf": true,
                  "content": "1",
                  "isSimple": false,
                  "childNodes": []
                },
                {
                  "nodeId": "b-1607152742827",
                  "pageId": "p-1607152742791-/pages/index/index",
                  "type": "text",
                  "content": "段中间插入了span的文本",
                  "className": "",
                  "isImage": false,
                  "useTemplate": false,
                  "isLeaf": false,
                  "isSimple": false,
                  "childNodes": []
                }
              ]
            }
          ]
        },
        {
          "nodeId": "b-1607152742829",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742830",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "div",
          "id": "",
          "className": "h5-div node-b-1607152742830 ",
          "style": "margin:20px;",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": true,
          "content": "",
          "childNodes": [
            {
              "nodeId": "b-1607152742831",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "p",
              "id": "",
              "className": "h5-p node-b-1607152742831 ",
              "style": "width:10rem;",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": true,
              "content": "这段看起来特别特别长的文字宽度是 10 rem，测试测试测试测试测试测试测试测试测试测试测试测试",
              "isSimple": false,
              "childNodes": []
            }
          ]
        },
        {
          "nodeId": "b-1607152742833",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "text",
          "content": " ",
          "className": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": false,
          "childNodes": []
        },
        {
          "nodeId": "b-1607152742834",
          "pageId": "p-1607152742791-/pages/index/index",
          "type": "element",
          "tagName": "div",
          "id": "",
          "className": "h5-div node-b-1607152742834 footer",
          "style": "",
          "isImage": false,
          "useTemplate": false,
          "isLeaf": false,
          "isSimple": true,
          "content": "",
          "childNodes": [
            {
              "nodeId": "b-1607152742835",
              "pageId": "p-1607152742791-/pages/index/index",
              "type": "element",
              "tagName": "p",
              "id": "",
              "className": "h5-p node-b-1607152742835 ",
              "style": "",
              "isImage": false,
              "useTemplate": false,
              "isLeaf": true,
              "content": "wechat-miniprogram",
              "isSimple": false,
              "childNodes": []
            }
          ]
        }
      ]
    }
  ]